"""Add quiz question cache table

Revision ID: 6838182998a9
Revises: e9ffcf9b57a8
Create Date: 2026-05-28 22:39:21.493208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6838182998a9'
down_revision = 'e9ffcf9b57a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_question_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('quiz_type', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('distractor_options', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('generation_quality_score', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_question_cache', schema=None) as batch_op:
        batch_op.create_index('ix_quiz_question_cache_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('ix_quiz_question_cache_vocab_type', ['vocabulary_id', 'quiz_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_question_cache_vocab_type')
        batch_op.drop_index('ix_quiz_question_cache_difficulty')

    op.drop_table('quiz_question_cache')
    # ### end Alembic commands ###
