"""add enrichment quality fields to search vocabulary

Revision ID: af360b35b11a
Revises: 6838182998a9
Create Date: 2026-05-29 15:09:46.478382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af360b35b11a'
down_revision = '6838182998a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_vocabulary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrichment_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_fully_enriched', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_vocabulary', schema=None) as batch_op:
        batch_op.drop_column('is_fully_enriched')
        batch_op.drop_column('enrichment_score')

    # ### end Alembic commands ###
