"""add validation status and timestamp

Revision ID: e9ffcf9b57a8
Revises: b1f4d8a6c902
Create Date: 2026-05-27 06:07:47.590661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ffcf9b57a8'
down_revision = 'b1f4d8a6c902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_history_user_created'))

    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_session_user_created'))

    with op.batch_alter_table('vocabulary_enrichment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('generation_timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vocabulary_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_master_last_audited'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_master_needs_admin_review'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_master_needs_admin_review'), ['needs_admin_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_master_last_audited'), ['last_audited_at'], unique=False)

    with op.batch_alter_table('vocabulary_enrichment', schema=None) as batch_op:
        batch_op.drop_column('generation_timestamp')
        batch_op.drop_column('validation_status')

    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_session_user_created'), ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('quiz_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_history_user_created'), ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###
